import {
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faBuilding, // Ícono para Departamentos
  faCalendarAlt,
  faChartLine, // Ícono para Seguimiento
  faCheck,
  faClipboardList, // Ícono para Solicitudes
  faCloud,
  faCogs,
  faDatabase,
  faDownload, // Ícono de Descargar (¡El que rompía tu tabla!)
  faEye,
  faFileAlt, // Ícono para Archivos
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faBuilding, // Añadido
  faCalendarAlt,
  faChartLine, // Añadido
  faCheck,
  faClipboardList, // Añadido
  faCloud,
  faCogs,
  faDatabase,
  faDownload, // Añadido
  faEye,
  faFileAlt, // Añadido
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  // jhipster-needle-add-icon-import
];
