logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.mycompany.myapp: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true

  docker:
    compose:
      enabled: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/PGestion_360
    username: postgres
    password: 1234
    pool:
      initial-size: 5
      max-size: 20

  liquibase:
    contexts: dev, faker
    url: jdbc:postgresql://localhost:5432/PGestion_360
    user: postgres
    password: 1234

  codec:
    max-in-memory-size: 100MB
  webflux:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # --- CONFIGURACIÓN DE CORREO  ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: usuario.prueba@localhost.com
    password: TU_PASSWORD_AQUI
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

server:
  port: 8080
  forward-headers-strategy: native

jhipster:
  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: Njk1MjNhYjU1ZDYzY2E3MWU5Mzg0YjBjYmExMmI2OTU0ZDQ3MDAxNjMwMWZkMzUyNWViNDI2ZGQ3ODE2OTc5OThiOTkwYzk3MjRmZGM2MTE2N2UzNjNjMDc3NzFkYzQwMzU3YmY3OGM0YTE5NGRkYWQ3ZjQ4OTM2MzE5YjI0ODQ=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
