package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CatalogueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogueAllPropertiesEquals(Catalogue expected, Catalogue actual) {
        assertCatalogueAutoGeneratedPropertiesEquals(expected, actual);
        assertCatalogueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogueAllUpdatablePropertiesEquals(Catalogue expected, Catalogue actual) {
        assertCatalogueUpdatableFieldsEquals(expected, actual);
        assertCatalogueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogueAutoGeneratedPropertiesEquals(Catalogue expected, Catalogue actual) {
        assertThat(actual)
            .as("Verify Catalogue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogueUpdatableFieldsEquals(Catalogue expected, Catalogue actual) {
        assertThat(actual)
            .as("Verify Catalogue relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogueUpdatableRelationshipsEquals(Catalogue expected, Catalogue actual) {
        // empty method
    }
}
