package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChangeRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestAllPropertiesEquals(ChangeRequest expected, ChangeRequest actual) {
        assertChangeRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertChangeRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestAllUpdatablePropertiesEquals(ChangeRequest expected, ChangeRequest actual) {
        assertChangeRequestUpdatableFieldsEquals(expected, actual);
        assertChangeRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestAutoGeneratedPropertiesEquals(ChangeRequest expected, ChangeRequest actual) {
        assertThat(actual)
            .as("Verify ChangeRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestUpdatableFieldsEquals(ChangeRequest expected, ChangeRequest actual) {
        assertThat(actual)
            .as("Verify ChangeRequest relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getUpdatedDate()).as("check updatedDate").isEqualTo(expected.getUpdatedDate()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getImpact()).as("check impact").isEqualTo(expected.getImpact()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFechaEntrega()).as("check fechaEntrega").isEqualTo(expected.getFechaEntrega()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getArchivoAdjunto()).as("check archivoAdjunto").isEqualTo(expected.getArchivoAdjunto()))
            .satisfies(a ->
                assertThat(a.getArchivoAdjuntoContentType())
                    .as("check archivoAdjunto contenty type")
                    .isEqualTo(expected.getArchivoAdjuntoContentType())
            )
            .satisfies(a -> assertThat(a.getSolicitante()).as("check solicitante").isEqualTo(expected.getSolicitante()))
            .satisfies(a -> assertThat(a.getDepartamento()).as("check departamento").isEqualTo(expected.getDepartamento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestUpdatableRelationshipsEquals(ChangeRequest expected, ChangeRequest actual) {
        assertThat(actual)
            .as("Verify ChangeRequest relationships")
            // --- CAMBIADO DE RESPONSIBLE A USER ---
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            // --------------------------------------
            .satisfies(a -> assertThat(a.getItemCatalogue()).as("check itemCatalogue").isEqualTo(expected.getItemCatalogue()));
    }
}
