package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FileRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileRecordAllPropertiesEquals(FileRecord expected, FileRecord actual) {
        assertFileRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertFileRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileRecordAllUpdatablePropertiesEquals(FileRecord expected, FileRecord actual) {
        assertFileRecordUpdatableFieldsEquals(expected, actual);
        assertFileRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileRecordAutoGeneratedPropertiesEquals(FileRecord expected, FileRecord actual) {
        assertThat(actual)
            .as("Verify FileRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileRecordUpdatableFieldsEquals(FileRecord expected, FileRecord actual) {
        assertThat(actual)
            .as("Verify FileRecord relevant properties")
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFilePath()).as("check filePath").isEqualTo(expected.getFilePath()))
            .satisfies(a -> assertThat(a.getFileType()).as("check fileType").isEqualTo(expected.getFileType()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a ->
                assertThat(a.getContentContentType()).as("check content contenty type").isEqualTo(expected.getContentContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileRecordUpdatableRelationshipsEquals(FileRecord expected, FileRecord actual) {
        assertThat(actual)
            .as("Verify FileRecord relationships")
            .satisfies(a -> assertThat(a.getChangeRequest()).as("check changeRequest").isEqualTo(expected.getChangeRequest()));
    }
}
