package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ItemCatalogueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCatalogueAllPropertiesEquals(ItemCatalogue expected, ItemCatalogue actual) {
        assertItemCatalogueAutoGeneratedPropertiesEquals(expected, actual);
        assertItemCatalogueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCatalogueAllUpdatablePropertiesEquals(ItemCatalogue expected, ItemCatalogue actual) {
        assertItemCatalogueUpdatableFieldsEquals(expected, actual);
        assertItemCatalogueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCatalogueAutoGeneratedPropertiesEquals(ItemCatalogue expected, ItemCatalogue actual) {
        assertThat(actual)
            .as("Verify ItemCatalogue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCatalogueUpdatableFieldsEquals(ItemCatalogue expected, ItemCatalogue actual) {
        assertThat(actual)
            .as("Verify ItemCatalogue relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getCatalogueCode()).as("check catalogueCode").isEqualTo(expected.getCatalogueCode()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCatalogueUpdatableRelationshipsEquals(ItemCatalogue expected, ItemCatalogue actual) {
        assertThat(actual)
            .as("Verify ItemCatalogue relationships")
            .satisfies(a -> assertThat(a.getCatalogue()).as("check catalogue").isEqualTo(expected.getCatalogue()));
    }
}
