package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResponsibleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsibleAllPropertiesEquals(Responsible expected, Responsible actual) {
        assertResponsibleAutoGeneratedPropertiesEquals(expected, actual);
        assertResponsibleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsibleAllUpdatablePropertiesEquals(Responsible expected, Responsible actual) {
        assertResponsibleUpdatableFieldsEquals(expected, actual);
        assertResponsibleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsibleAutoGeneratedPropertiesEquals(Responsible expected, Responsible actual) {
        assertThat(actual)
            .as("Verify Responsible auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsibleUpdatableFieldsEquals(Responsible expected, Responsible actual) {
        assertThat(actual)
            .as("Verify Responsible relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsibleUpdatableRelationshipsEquals(Responsible expected, Responsible actual) {
        // empty method
    }
}
