package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrackingRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingRecordAllPropertiesEquals(TrackingRecord expected, TrackingRecord actual) {
        assertTrackingRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertTrackingRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingRecordAllUpdatablePropertiesEquals(TrackingRecord expected, TrackingRecord actual) {
        assertTrackingRecordUpdatableFieldsEquals(expected, actual);
        assertTrackingRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingRecordAutoGeneratedPropertiesEquals(TrackingRecord expected, TrackingRecord actual) {
        assertThat(actual)
            .as("Verify TrackingRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingRecordUpdatableFieldsEquals(TrackingRecord expected, TrackingRecord actual) {
        assertThat(actual)
            .as("Verify TrackingRecord relevant properties")
            .satisfies(a -> assertThat(a.getChangeDate()).as("check changeDate").isEqualTo(expected.getChangeDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getComments()).as("check comments").isEqualTo(expected.getComments()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingRecordUpdatableRelationshipsEquals(TrackingRecord expected, TrackingRecord actual) {
        assertThat(actual)
            .as("Verify TrackingRecord relationships")
            .satisfies(a -> assertThat(a.getResponsible()).as("check responsible").isEqualTo(expected.getResponsible()))
            .satisfies(a -> assertThat(a.getChangeRequest()).as("check changeRequest").isEqualTo(expected.getChangeRequest()));
    }
}
